# Generated by Django 3.1.5 on 2021-02-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='card_image',
            field=models.CharField(default='services/GI_logo_extended.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='call_to_action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
    ]
